export const AFFIRMATIONS = [
    "I am worthy of love, success, and happiness.",
    "I trust in my ability to navigate life's challenges.",
    "Every day, I am growing stronger and wiser.",
    "I choose to focus on what I can control.",
    "My potential is limitless and I embrace it fully.",
    "I am grateful for all the good in my life.",
    "I deserve to take up space and be heard.",
    "My mistakes do not define me; they help me grow.",
    "I am capable of creating positive change in my life.",
    "I choose peace over worry and love over fear.",
    "My thoughts have power, and I choose positive ones.",
    "I am exactly where I need to be right now.",
    "I trust the timing of my life's journey.",
    "I am resilient and can overcome any obstacle.",
    "My uniqueness is my superpower.",
    "I attract abundance and opportunities into my life.",
    "I am proud of how far I've come.",
    "Every challenge is an opportunity to grow stronger.",
    "I radiate confidence and self-assurance.",
    "I am the author of my own story.",
    "My dreams are valid and achievable.",
    "I choose to see the beauty in everyday moments.",
    "I am deserving of respect and kindness.",
    "My inner wisdom guides me to make the right decisions.",
    "I release what no longer serves me.",
    "I am open to receiving all the good life has to offer.",
    "My energy is powerful and magnetic.",
    "I trust in my ability to heal and grow.",
    "I am creating a life I love living.",
    "Every breath I take fills me with peace and clarity.",
    "I am enough, exactly as I am right now.",
    "My presence makes a positive difference in the world.",
    "I choose courage over comfort.",
    "I am aligned with my highest purpose.",
    "My heart is open to giving and receiving love.",
    "I celebrate my progress, no matter how small.",
    "I am the architect of my own happiness.",
    "My intuition is strong and trustworthy.",
    "I embrace change as a catalyst for growth.",
    "I am surrounded by love and support.",
    "My mind is clear and focused on my goals.",
    "I choose to speak kindly to myself.",
    "I am creating healthy boundaries in my life.",
    "My passion and enthusiasm are contagious.",
    "I trust that everything happens for my highest good.",
    "I am becoming the person I'm meant to be.",
    "My creativity flows freely and abundantly.",
    "I choose to see opportunities instead of obstacles.",
    "I am worthy of pursuing my dreams.",
    "My self-love grows stronger every day.",
    "I am at peace with my past and excited for my future.",
    "I choose to respond with grace under pressure.",
    "My life is filled with infinite possibilities.",
    "I am grateful for my body and treat it with respect.",
    "I attract positive, supportive people into my life.",
    "My thoughts create my reality, and I choose wisely.",
    "I am confident in my ability to solve problems.",
    "I choose joy and optimism as my default state.",
    "I am deserving of success in all areas of my life.",
    "My authentic self is my greatest asset.",
    "I trust in the process of life unfolding perfectly.",
    "I am a magnet for miracles and blessings.",
    "My determination is stronger than any challenge.",
    "I choose to learn and grow from every experience.",
    "I am creating a legacy of love and kindness.",
    "My spirit is unbreakable and eternally hopeful.",
    "I choose to see the good in myself and others.",
    "I am worthy of taking time for self-care.",
    "My goals are achievable through consistent action.",
    "I trust my ability to make decisions that serve me.",
    "I am grateful for the lessons in every situation.",
    "My confidence grows with every step I take.",
    "I choose to forgive myself and others with compassion.",
    "I am surrounded by abundance in all forms.",
    "My energy attracts what I desire most.",
    "I choose to focus on solutions rather than problems.",
    "I am worthy of healthy, loving relationships.",
    "My inner strength carries me through any storm.",
    "I choose to honor my needs and desires.",
    "I am open to new experiences and adventures.",
    "My life has meaning and purpose.",
    "I choose to be patient with my growth process.",
    "I am deserving of financial abundance and security.",
    "My heart is filled with gratitude and contentment.",
    "I choose to see setbacks as setups for comebacks.",
    "I am capable of achieving anything I set my mind to.",
    "My words have power, and I use them wisely.",
    "I choose to celebrate my uniqueness and individuality.",
    "I am worthy of respect in all my relationships.",
    "My future is bright and full of possibilities.",
    "I choose to trust the wisdom of my heart.",
    "I am creating positive momentum in my life.",
    "My presence brings light to those around me.",
    "I choose to release perfectionism and embrace progress.",
    "I am grateful for my journey and where it's leading me.",
    "My dreams are coming true in perfect timing.",
    "I choose to be gentle with myself as I grow.",
    "I am worthy of living a life that excites me.",
    "My inner peace is unshakeable and constant.",
    "I choose to focus on what brings me joy.",
    "I am creating a beautiful, meaningful life.",
    "My potential expands with every new day.",
    "I choose to believe in myself unconditionally.",
    "I am deserving of all the happiness life offers.",
    "My spirit is free and unlimited in its power."
]