export const PROMPTS = [
"What are three things you’re proud of this week?",
"What limiting beliefs are holding you back?",
"Describe a moment today when you felt truly present.",
"How do you define success for yourself?",
"What have you learned about yourself this year?",
"What makes you feel most alive?",
"What are you avoiding right now, and why?",
"Who do you become when no one is watching?",
"What emotion have you been suppressing lately?",
"What does your ideal day look like?",
"What habit are you trying to build?",
"What does discipline mean to you?",
"What distractions keep you from growing?",
"When do you feel most focused and why?",
"What small change could improve your life?",
"How do you stay consistent when motivation fades?",
"What would your life look like if you showed up fully?",
"What does \"being better than yesterday\" mean to you?",
"In what ways have you already grown this year?",
"What triggers you — and how can you respond differently?",
"What made you feel anxious today? Why?",
"How did you show yourself kindness recently?",
"What negative thought keeps coming up? Challenge it.",
"What are three things that bring you peace?",
"How do you handle discomfort?",
"What’s one fear you want to face?",
"What’s something you can forgive yourself for?",
"When was the last time you felt pure joy?",
"How do you recharge emotionally?",
"Write a letter to your future self.",
"What goal excites you most right now?",
"Where do you see yourself in 5 years?",
"What would you do if you knew you couldn’t fail?",
"What’s stopping you from starting?",
"Why does your current goal matter to you?",
"What would your highest self prioritize today?",
"How do you measure personal progress?",
"Describe your dream lifestyle in vivid detail.",
"What projects or goals have you abandoned — and why?",
"What legacy do you want to leave?",
"Who do you feel most yourself around? Why?",
"How do you show love to others?",
"What relationship needs more of your attention?",
"What boundaries do you need to set?",
"How do you handle conflict? What could you improve?",
"Who inspires you to be a better person?",
"When did someone truly listen to you?",
"Write about someone you miss.",
"What’s something kind you want to say to someone?",
"How do you want to be remembered by the people closest to you?",
"What does your gut say about your current path?",
"What would your inner child say about your life now?",
"Describe a moment when you felt aligned with your purpose.",
"What signs or patterns keep showing up in your life?",
"What’s your intuition telling you today?",
"When do you feel most spiritually grounded?",
"What questions are you afraid to ask yourself?",
"Write down 3 things you know deep down — but don’t often say.",
"What does “trusting yourself” look like in practice?",
"What advice would you give to your younger self?",
"List five things you're grateful for today.",
"What’s something simple that brings you joy?",
"What’s a recent win you haven’t celebrated?",
"Who has made a positive impact on your life lately?",
"What’s something about your body that you’re thankful for?",
"What made you smile today?",
"Write about a challenge that taught you something.",
"What memory always warms your heart?",
"What’s a privilege in your life that you often overlook?",
"What good things are already in motion?",
"What did you learn about yourself today?",
"What went well today?",
"What could have gone better — and how will you adjust?",
"What are you looking forward to tomorrow?",
"What emotion dominated your day?",
"Did you show up authentically today?",
"What was one moment you’d like to remember from today?",
"What’s one thing you need to let go of tonight?",
"How did you take care of yourself today?",
"What was the best part of your day?",
"If your life was a movie, what scene are you in now?",
"Write a letter to fear — what would you say?",
"Imagine a future where everything works out. What does it look like?",
"If you could talk to the universe, what would you ask?",
"What do you dream about when no one’s watching?",
"Describe your happiest memory as a short story.",
"Invent a new version of yourself. What is their routine?",
"What does your personal utopia look like?",
"If you had unlimited time, what would you create?",
"Create a mantra that you can live by this week.",
"What makes you unique?",
"What’s something you wish people knew about you?",
"What drives you on hard days?",
"How do you define “enough”?",
"What identity are you growing into?",
"What does self-respect look like in your daily life?",
"What does your silence usually mean?",
"What do you want to be known for?",
"What’s one truth you’ve been avoiding?",
"Who are you becoming?"
]